Show error line number if s3-cp has an error

diff --git a/modules/s3/s3-cp b/modules/s3/s3-cp
--- a/modules/s3/s3-cp
+++ b/modules/s3/s3-cp
@@ -12,6 +12,13 @@ function cleanup {
   echo "✓ Deleted temp working directory $TMP"
 }
 
+function error {
+  echo "✗ Error from s3-cp on line $1"'!'
+  exit 1
+}
+trap 'error ${LINENO}' ERR
+
+
 BUCKET=$1
 [ -z "$BUCKET" ] && usage
 
