updated - `make dashboard`
- works on some linuxs now
- basic cluster health check

diff --git a/scripts/dashboard b/scripts/dashboard
--- a/scripts/dashboard
+++ b/scripts/dashboard
@@ -1,6 +1,22 @@
-#!/bin/bash -eu
+#!/bin/bash -u
+
+case "${OSTYPE}" in
+ linux*)
+    OPEN="xdg-open"
+    ;;
+ darwin*)
+    OPEN="open"
+    ;;
+esac
+
+command -v ${OPEN} &> /dev/null
+[ $? -ne 0 ] && ( echo "cannot determine 'open' command" ; exit 1 )
+
+kubectl cluster-info &> /dev/null
+[ $? -ne 0 ] && ( echo "cluster is not healthy" ; exit 1 )
 
 kubectl proxy &
 echo "✓ kubectl proxy is listening"
-open http://localhost:8001/ui
+
+${OPEN} http://localhost:8001/ui
 sleep 1 && echo " "
